### ISSUE TITLE
Problem in main.go cannot use beater.New.

### ISSUE THREAD

**Issue by freshteapot** [phenomenes/varnishbeat#1]
First I installed "libvarnishapi-dev" to get access to varnishapi.pc.

```
apt-get install libvarnishapi-dev
```

Then when I tried using "go get". I got the following error.

```
./main.go:12: cannot use beater.New() (type *beater.Varnishbeat) as type beat.Creator in argument to beat.Run
```

Any thoughts on what I am doing wrong? :)

**Comment by phenomenes** [comment]
First issue can be solved by following the vago package installation instructions here: https://github.com/phenomenes/vago/blob/master/README.md
I'll update the documentation, thanks for the heads up.

Second issue is because the beats package recently introduced some changes. I'm working on a fix.
