### ISSUE TITLE
Run Varnishbeat: flag provided but not defined: -log

### ISSUE THREAD

**Issue by thangamani-arun** [phenomenes/varnishbeat#4]
After building varnishbeat, not able to run the varnishbeat with -log and -stats options, getting below errors

/home/ubuntu/varnishbeat-go/bin/varnishbeat -log -c /home/ubuntu/varnishbeat-go/bin/varnishbeat.yml                          flag provided but not defined: -log
Usage of /home/ubuntu/varnishbeat-go/bin/varnishbeat:
  -E value
        Configuration overwrite (default null)
  -N    Disable actual publishing for testing
  -c path
        Configuration file path (default /home/ubuntu/varnishbeat-go/bin/varnishbeat.yml)
  -configtest
        Test configuration and exit.
  -cpuprofile string
        Write cpu profile to file
  -d string
        Enable certain debug selectors
  -e    Log to stderr and disable syslog/file output
  -httpprof string
        Start pprof http server
  -memprofile string
        Write memory profile to this file
  -path.config value
        Configuration path
  -path.data value
        Data path
  -path.home value
        Home path
  -path.logs value
        Logs path
  -v    Log at INFO level
  -version
        Print the version and exit

**Comment by phenomenes** [comment]
The `-log` and `-stats` flags were removed in the latest commit, you need to define the mode in the yaml configuration file:

Add this to `varnishlogbeat.yml`:
```yaml
varnishbeat:
  log: true
```

I'll update the README, thanks for the heads up.

**Comment by thangamani-arun** [comment]
Thanks, it works for me.

I'm generating additional logs in VSM, is there a way to set those additional tags in beat? so that i can collect additional fields along with existing varnishlog fields at ELK.
