### ISSUE TITLE
 Exiting: error initializing publisher: Error loading template varnishbeat.template-es2x.json: open varnishbeat.template-es2x.json: no such file or directory

### ISSUE THREAD

**Issue by thangamani-arun** [phenomenes/varnishbeat#6]
I'm trying to use template.json and customize the filed mappings for elastficsearch. But while using the template, getting errors and not able to use templates

**varnishlogbeat.yml**

> output:
>   elasticsearch:
>     hosts: ["10.0.0.7:9200"]
>     index: "varnishbeatlog"
>     template.enabled: true
>     template.name: "varnishlogbeat"
>     template.path: "/root/varnishbeat/varnishlogbeat.template.json"
>     template.overwrite: true
> 
> logging:
>     level: "debug"
> 
> varnishbeat:
>     log: true

**Execute:** 

> varnishbeat  -c varnishlogbeat.yml

**Error:**

> Exiting: error initializing publisher: Error loading template /root/varnishbeat/varnishbeat.template-es2x.json: open /root/varnishbeat/varnishbeat.template-es2x.json: no such file or directory

**Comment by thangamani-arun** [comment]
I resolved above error by adding additional config in varnishlogbeat.yml file as follows

>  template.versions.2x.enabled: false

But, it sends all the messages to Elastic search instead of my custom fileds( custom JSON /root/varnishbeat/varnishlogbeat.template.json)

It looks like does not map fields using my custom JSON template file. Kindly suggest me possible way to fix this issue.

**Comment by thangamani-arun** [comment]
@phenomenes @freshteapot Any idea would help me to find the issue. Thanks

**Comment by phenomenes** [comment]
Sorry for taking so long to respond.

I'm afraid that is not a problem with varnishbeat, if you require support about elasticsearch I'll suggest you post a question on their forum: https://discuss.elastic.co/
